apiVersion: apps/v1
kind: Deployment 
metadata:
  name: paymentservice 
  labels:
    app: paymentservice
spec:
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - image: alekskar/hipster-paymentservice:v0.0.2
        name: paymentservice
